# Use the official Node.js LTS image as the base image
FROM node:16-bullseye AS development

RUN npm install -g bun

RUN bun install -g @nestjs/cli

WORKDIR /usr/src/app

COPY package*.json ./

RUN bun install

# RUN npm install glob rimraf

# RUN npm install --only=development

COPY . .

# Set the development stage as the final stage
FROM development AS final

CMD ["bun", "run", "--watch", "main.ts"]
